spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/tamil
spring.datasource.username=root
spring.datasource.password=Tamilvanan2004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
server.port=8080
